apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yasinhirsi/EKS-ArgoCD-Helm.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

      